SELECT S.SURNAME AS "Surname", M.subjects_SUBJ_ID AS "ID of subject"
FROM student S
LEFT JOIN exam_marks M ON S.STUDENT_ID = M.student_STUDENT_ID
ORDER BY S.SURNAME;

SELECT S.SURNAME AS "Surname", U.RATING AS "RATING"
FROM student S
LEFT JOIN university U ON S.UNIVERSITY_UNIV_ID = U.UNIV_ID
ORDER BY S.SURNAME;

SELECT S.SURNAME AS "Surname", Sub.SUBJ_NAME AS "Subject", M.MARK AS "Mark"
FROM student S
JOIN exam_marks M ON S.STUDENT_ID = M.student_STUDENT_ID
JOIN subjects Sub ON M.subjects_SUBJ_ID = Sub.SUBJ_ID
WHERE M.MARK IN (4, 5)
GROUP BY S.SURNAME, Sub.SUBJ_NAME, M.MARK
HAVING MIN(M.MARK) >= 4
ORDER BY S.SURNAME;

SELECT S1.SURNAME AS "Student 1", S2.SURNAME AS "Student 2", S1.CITY AS "City"
FROM student S1
JOIN student S2 ON S1.CITY = S2.CITY AND S1.STUDENT_ID < S2.STUDENT_ID
ORDER BY S1.SURNAME;