# application.properties
spring.application.name=Biglaba1

# binary, octal, hex
converter.type=binary

# false / true
interactive.mode=true

numbers.to.convert=10,20,30,40,50,100,255,512,1000,2048,4096


logging.pattern.console=%d{HH:mm:ss.SSS} - %msg%n
